### ISSUE TITLE
disableLosslessIntegers 

### ISSUE THREAD

**Issue by tansuozhe123** [cemremengu/egg-neo4j#1]
您好，请问egg-neo4j支持disableLosslessIntegers吗？？

**Comment by cemremengu** [comment]
Hello I am not sure actually since I dont use it anymore. Feel free to send a PR and I will patch it.

**Comment by tansuozhe123** [comment]
neo4j-javascript-driver支持disableLosslessIntegers参数，当disableLosslessIntegers:flase的时候，查询返回的数字类型不是{low:"",high:""}这样的格式，而是正常的数字类型，但会存在数据溢出的危险。
